FROM node:15.4.0-alpine as alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY package-lock.json /app

RUN npm i --silent
RUN npm i react-scripts@3.4.1 -g silent

COPY . ./

CMD ["npm", "start"]